name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v4
      - run: mix local.hex --force
      - name: Publish Parameter
        run: mix do deps.get, hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
